version: "3"

services:
  postgresql:
    image: "postgres:12.5"
    ports:
      - 5432:5432
    volumes:
      - postgres_data_container:/data/db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=forum
volumes:
  postgres_data_container:
